fix the collector config
CloudDectective-Harmonycloud/kindling pull request #225
Opened 2022-05-16 06:38 UTC by yaofighting

Signed-off-by: yaofighting <siyao@zju.edu.cn>

fix the collector config and make it running normally on the Linux environment
## Description

in the file /root/kindling/collector/docker/kindling-collector-config.yml, we can see a bug about that we may not boot the collector normally in the Linux environment due to the "kube_config_dir" is "~" instead of "root", so in this PR, I fix it.
## Related Issue

https://github.com/Kindling-project/kindling/issues/224
## Motivation and Context

it fix the compatibility of collector
## How Has This Been Tested?

just compile and build the collector container with the doc's step.

2022-05-16 09:29 UTC, dxsup requested changes
There is another configuration file under the directory `kindling/deploy`. Although it is using `serviceaccount` as its `kube_auth_type` and `kube_config_dir` isn't effective, I think we better make this field same to avoid misunderstanding.

2022-05-16 09:29 UTC, dxsup commented on collector/docker/kindling-collector-config.yml
> +    kube_config_dir: root/.kube/config
Should be started with "/".

2022-05-17 03:24 UTC, yaofighting commented on collector/docker/kindling-collector-config.yml
> +    kube_config_dir: root/.kube/config
OK, it has been modified as required

2022-05-17 05:43 UTC, dxsup approved these changes
LGTM

2022-05-17 05:43 UTC, merged